FROM openjdk:17-alpine

VOLUME /app-src
VOLUME /output
ARG JAR_FILE=target/build-tool-version-plugin-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} java-application.jar
ENTRYPOINT [ "java", "-jar",  "java-application.jar" ]